notifications:
  email:
    on_success: change
language: python

branches:
  only:
    - main
    - development

jobs:
  include:
    - stage: "Unit tests"
      name: "Unit tests on python 3.6"
      python: "3.6"
      install:
        - pip install -r requirements.txt
      script:
        - python -m unittest -v
    
    - name: "Unit tests on python 3.7"
      python: "3.7"
      install:
        - pip install -r requirements.txt
      script:
        - python -m unittest -v

    - name: "Unit tests on python 3.8"
      python: "3.8"
      install:
        - pip install -r requirements.txt
      script:
        - python -m unittest -v

    - name: "Unit tests on python 3.9"
      python: "3.9"
      install:
        - pip install -r requirements.txt
      script:
        - python -m unittest -v


    - stage: "Integration Test"
      name: "Integration tests on python 3.6"
      python: "3.6"
      install:
        - pip install -r requirements.txt
        - pip install .
        - /bin/bash ci/start_weaviate.sh
      script:
        - python -m integration.client_functions

    - name: "Integration tests on python 3.7"
      python: "3.7"
      install:
        - pip install -r requirements.txt
        - pip install .
        - /bin/bash ci/start_weaviate.sh
      script:
        - python -m integration.client_functions

    - name: "Integration tests on python 3.8"
      python: "3.8"
      install:
        - pip install -r requirements.txt
        - pip install .
        - /bin/bash ci/start_weaviate.sh
      script:
        - python -m integration.client_functions

    - name: "Integration tests on python 3.9"
      python: "3.9"
      install:
        - pip install -r requirements.txt
        - pip install .
        - /bin/bash ci/start_weaviate.sh
      script:
        - python -m integration.client_functions

env:
  global:
  - secure: "a0ZLXu2ysKDW3WSN4U8z9d8+kPJ626o9t706zUWLJmEe+oGuVy1bMrALLU4zeZch1tZu4V/k2OiSCJYRYOVXUBfVCCTqcZXkUpJgr4rLF/e3OoVu17TCrikYUX3KXmJc3VmgFslBCL7qxUrnDBrnt7w4qwrmgRGK9ZdF8SyzLPcnW7AEwe5ZLkDKl26G7hD3TUnRiswAiN3NuAyx0/dq2VryJX74Szdyrm8Wo8fr1L+p2Mpp+73169EP9AO5lCpAjgNaNcmdA7QlxZVXHWt0WE7oaj4fve+ZSxR6AJcOUTRZg5xyBzbqneOsV7dT3HuZesNSevlQ+HgfRVqsEFscetiI4fYAXZVPlLE2Pm3OX+rzqr6HVvtP6TkqtZNUAHKEdXMsTZbTAAePWUjaDPnGqjKEh5yuzrLEC6Gq4lS1ami24ukkvriNxILkKduEdqz4b1D4wMpOFpF5WfkHwrDTcZXDo1XtR4q1pYi/N5QyXehxHtAtapZoLPu2jjOw1iVHTXGgmlq/HtundgtaKnoy/Rcrt/pd7MuHf859Ugkpx8hvgJ47UobeZWjGmgTbq3w+hgrxqWnNXYb2kdPTDxAOF5AV3i2EdM/G9vE0lDsvZZPotVssWbuy1TlmAmgrhndD05D8PBh9+XU4xTbUOmstMFbNaWSYZ8jCuMZtz34fEtA="
  - secure: "b3xMkFpr0PfY7yBfkE4uJBlQqH0235zK6yynqVweJ+t/v8MdYmz65H8E5Ha+BG9u4FGT+M1BiBnZZowuRkDOqooU+v89254JQSbp62yTnqgI9BArOxMLgWSXezedZ5qqN0fe4g/Ke+yIpPDUXHyMd4w46xQOwxZepgscFUOsJmCPe16z1k5w5GZxO7GqJK6wMitBSiqOeah5+ASni1H5yswXnSEnYHtL9e7WhB+ykIMv8tA8W8c4qkx5szPfzipwEe8GT0ANZK/6ayJIz8iJbitXeDzrYSKBfmvrE4XSfv2gRTb3oamIqZm3WyDH088c/goYS+JiiWKlRKqEoivqRX5H4ozo+wZS3rfbBEHO7+i0AeAEy7cTD7i+ZBlc8lH5VE0D5bP6WxaKrLcPN98i1F8bPFeyVQdzD8yoCWQTv5A5hQ9tJCmtK8fPTGOLzVjXR0StGEgIoLiNccKtS8aZ1prb1iIyiAwQJaxmeoOCvfOmPdaZbkInNkKFiTUZLyd+uc9jNbVZRWWSQyKXP5bDOiCzhKFGNsgusy7LPF5QmlqgMDdNniVV0rG8gO6YsWzSeFfJkTTpwYDNHySc2iW22V6jtmEEdlVrlGWNOmd/NiNONGSWIpG3cq16BTFuSsc7YyU/32tgu69aMmhDoWUCva8UDXJYGz1lpF6KeJ6i4hk="




before_script:
  # login to docker at the very beginning, so we don't run into rate-limiting
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

