---
version: '3.4'
services:
  weaviate_async:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8090'
      - --scheme
      - http
    image: semitechnologies/weaviate:preview-update-nodes-api-with-vectorindexingstatus-field-for-shards-5f2ea68
    ports:
      - "8090:8090"
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'
      ASYNC_INDEXING: 'true'
