name: Publish to PyPi and create GitHub Release

on:
  workflow_run:
    workflows: [Tests]
    types:
      - completed

permissions:
  contents: write

jobs:

  gh-release:
    name: Create a GitHub Release
    runs-on: ubuntu-latest
    needs: build-and-publish
    if: startsWith(github.ref, 'refs/tags') && ${{ github.ref_name == 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: true