name: Tests

on:
  push:
    branches:
      - main
    tags:
      - '**'
    paths-ignore:
      - docs/**
      - README.rst
      - LICENSE.md
      - publishing.md
  pull_request:

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.version }}
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - name: Run unittests
      run: pytest --cov --cov-report=term-missing --cov=weaviate --cov-report xml:coverage.xml test
    - name: Upload to codecov
      if: matrix.version == '3.10' && (github.ref_name != 'master')
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        files: coverage.xml
        flags: unittests

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
          cache: 'pip' # caching pip dependencies
      - run: |
          pip install -r requirements.txt
          pip install .
      - name: Run integration tests
        run: |
          /bin/bash ci/start_weaviate.sh
          pytest --cov --cov-report=term-missing --cov=weaviate --cov-report xml:coverage.xml integration
      - name: Upload to codecov
        if: matrix.version == '3.10' && (github.ref_name != 'master')
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: coverage.xml
          flags: unittests

  build-and-add-artifact:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    needs: [integration-tests, unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install wheel build
      - name: Build a binary wheel
        run: python setup.py bdist_wheel
      - name: Create Wheel Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: "dist/*.whl"
          retention-days: 7
